export const UPDATE_TICKETS = "UPDATE_TICKETS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_TEAMS = "UPDATE_TEAMS";
export const UPDATE_CURRENT_TEAM = "UPDATE_CURRENT_TEAM";
